stages:
  - build

variables:
  APPLICATION_NAME: camera-handler-fastapi
  CONTAINER_REGISTRY: 172.16.98.151:5000
  CONTAINER_TAG: ${CI_COMMIG_SHORT_SHA}
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}



build-prod:
  tags:
    - aarch64
  only:
    - master
  stage: build
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
